name: continuous integration
on:
  push:
    branches:
      - '**'
    paths:
      - '.github/**'
      - 'web/**'

jobs:

  env:
    runs-on: ubuntu-latest
    name: debug environment

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: env

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan -x test
      - name: Verify dependencies
        run: |
          COUNT=$(./gradlew -q dependencies | grep -c SNAPSHOT || true)

          echo "Found $COUNT SNAPSHOT dependencies"

          if [ "$COUNT" -gt 0 ]
          then
            >&2 echo ::error No SNAPSHOT dependencies allowed
            exit 1;
          fi
      - run: ./gradlew test --tests "*"

  integration:
    runs-on: ubuntu-latest
    name: Integration tests of jactor-web <-> jactor-persistence

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - uses: jactor-rises/jactor-persistence/run-docker@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE: ghcr.io/jactor-rises/jactor-persistence
      - run: ./gradlew test --tests "UserConsumerIntegrationTest"

  git:
    needs: [build, integration]
    if: github.ref == 'refs/heads/main'
    name: Tag new snapshot version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch current snapshot tag
        id: current
        run: |
          git fetch --tags
          CURRENT_SEMVER=$(git tag --sort=-v:refname --list "[0-9].[0-9].[0-9]*[-snapshot]" | sed 's;-snapshot;;'| head -n 1)
          echo ::set-output name=semver::$CURRENT_SEMVER
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --build-cache assemble
      - name: Fetch current major/minor release
        id: version
        run: |
          MAJOR_MINOR=$(./gradlew properties | grep version: | grep SNAPSHOT | awk '{print $2}' | sed 's;.x-SNAPSHOT;;')
          echo ::set-output name=toPatch::$MAJOR_MINOR
      - name: Create new semantic version
        id: semver
        run: |
          workflow/scripts/new-semver.main.kts majorMinor=$PATCH_MAJOR_MINOR_VERSION semantic=$CURRENT_SEMANTIC_VERSION
          echo ::set-output name=new::$(cat newSemVer)
        env:
          CURRENT_SEMANTIC_VERSION: ${{ steps.current.outputs.semver }}
          PATCH_MAJOR_MINOR_VERSION: ${{ steps.version.outputs.toPatch }}
      - name: Fetch github event metadata
        id: metadata
        run: |
          echo ::set-output name=email::$(jq .commits $GITHUB_EVENT_PATH | jq '.[].committer.email' | head -n 1)
          echo ::set-output name=name::$(jq .commits $GITHUB_EVENT_PATH | jq '.[].author.name' | head -n 1)
      - name: Tag new snapshot semantic version
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "$AUTHOR_EMAIL"
          git config --global user.name "$AUTHOR_NAME"

          git tag -a "$SEMANTIC_VERSION_NEW-snapshot" -m "New snapshot tagged. Previous snapshot: $SEMANTIC_VERSION_CURRENT"
          git push --tags
        env:
          AUTHOR_EMAIL: ${{ steps.metadata.outputs.email }}
          AUTHOR_NAME: ${{ steps.metadata.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_VERSION_CURRENT: ${{ steps.current.outputs.semver }}
          SEMANTIC_VERSION_NEW: ${{ steps.semver.outputs.new }}
